package com.yesset.booking.util;

public enum ErrorStatus {
    VALIDATION_ERROR,
    PULL_DATA_ERROR,
    BOOKING_ERROR,
    ACTIVE_BOOKING_ERROR,
    LATE_CANCEL_ERROR,
    SOURCE_NOT_FOUND_ERROR,
    FAVOURITE_CREATE_ERROR,
    FAVOURITE_DELETE_ERROR,

    /*
    Item
     */
    ITEM_CREATION_ERROR,
    ITEM_DELETION_ERROR,
    ITEM_MODIFICATION_ERROR,
    ITEM_CHECKIN_ERROR,
    ITEM_APPROVE_ERROR,
    ITEM_REJECT_ERROR,

    /*
    Rental
     */
    RENTAL_INTERSECTION_ERROR,
    RENTAL_LATE_CANCEL_ERROR,

    /*
    Review
     */
    REVIEW_CREATION_ERROR,
    REVIEW_DELETION_ERROR,
    REVIEW_MODIFICATION_ERROR,

    /*
    User Card
     */
    CARD_CREATION_ERROR,
    CARD_DELETION_ERROR
}
