spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: Booking
  datasource:
    url: jdbc:postgresql://localhost:5433/booking_system
    username: postgres
    password: 20112003b
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/main-data.xml
server:
  port: 8080
#springdoc:
#  swagger-ui:
#    path: /swagger-ui
#  api-docs:
#    path: /v3/api-docs


token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
