INSERT INTO t_user (username, password_hash, role_id, phone, firstname, lastname, middlename, profile_photo_url, birth_date, microdistrict_id, street) VALUES
                                                                                                                                                           ('transport_admin@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77089312586', 'Marat', 'Bakyt', 'Aiqynuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Marat+Bakyt.jpeg', '1987-03-25', 52, 'Улица Розы Багланова 77'),
                                                                                                                                                           ('electronics_gadgets_admin@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77079091233', 'Yeraly', 'Ruslanov', 'Nursultanuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Yeraly+Ruslanov.jpeg', '1997-09-07', 41, 'Улица Набережная Хамита Ергалиева 20'),
                                                                                                                                                           ('tools_equipment_admin@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77078563456', 'Aisultan', 'Kasymov', 'Aliuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Aisultan+Kasymov.jpeg', '1991-12-16', 17, 'Улица Фурката 60'),
                                                                                                                                                           ('clothing_accessories_admin@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77754634576', 'Ardak', 'Baidilda', 'Arystanuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Ardar+Baidilda.jpeg', '2001-07-23', 14, 'Улица неизвестная 20'),
                                                                                                                                                           ('entertainment_events_admin@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77053432376', 'Nurdaulet', 'Yernazarov', 'Darkhanuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Nurdaulet+Yernazarov.jpeg', '2000-02-05', 58, 'Улица Абишева 36/11'),
                                                                                                                                                           ('real_estate@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77084456785', 'Bakdaulet', 'Rakhatov', 'Sunkaruly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Bakdaulet+Rakhatov.jpeg', '1992-06-30', 20, '34'),
                                                                                                                                                           ('home_furniture@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77776782341', 'Yerdaulet', 'Bekzhan', 'Yernaruly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Yerdaulet+Bekzhan.jpeg', '1995-11-15', 15, '73'),
                                                                                                                                                           ('outdoor_sports_admin@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 1, '+77075089148', 'Aidar', 'Saken', 'Bekezhanuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Aidar+Saken.jpeg', '1994-10-17', 26, '8'),
                                                                                                                                                           ('b_dosmukhammedov@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 2, '+77057897890', 'Bakdaulet', 'Dosmukhammedov', 'Serikuly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Bakdaulet+Dosmukhamedov.jpeg', '1989-04-08', 30, 'улица Жунисова 2/13 к25'),
                                                                                                                                                           ('a_arnurova@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 2, '+77778796578', 'Ainur', 'Arnurova', 'Bolatqyzy', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Ainur+Arnurova.jpeg', '2000-05-13', 46, '6'),
                                                                                                                                                           ('a_qanysh@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 2, '+77083425765', 'Aisha', 'Qanysh', 'Ermekqyzy', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Aisha+Qanysh.jpeg', '2001-01-31', 31, '29'),
                                                                                                                                                           ('a_altynbekov@gmail.com', '$2a$10$dGV7hCuRLHyR46FdC0cmleT2uEv78Uyl8QSDY53jMgLnaV/7cBSqe', 2, '+77778798956', 'Aidarkhan', 'Altynbekov', 'Kaisaruly', 'https://booking-image-upload-bucket.s3.eu-north-1.amazonaws.com/profile_pictures/Aidarkah+Altynbekov.jpeg', '2003-05-20', 9, '68');
